
#Client only settings
[client]
	#Set to true to enable holding down the Trigger Elytra keybind to automatically use a firework from inventory to takeoff from ground level
	simpleTakeoff = true
	#Set to true to enable an icon that appears on the HUD when elytra flight is disabled
	toggleIcon = true
	#Set to true to enable jump triggering the elytra while falling as normal, false to disable.
	jumpTriggerable = true
	#Set to true to enable elytra flight as normal, false to disable elytra flight. This can also be managed in-game through the "Toggle Elytra" keybinding.
	enableElytra = true

